### ISSUE TITLE
Add classes for Address, Author, book, Customer, Order, Order-Details and User.

### ISSUE THREAD

**Issue by arpanghosh2414** [dsc-iem/E-Commerce-Website-Hacktoberfest2023#1]
The classes mentioned in the title should be designed for entity, repository, service, service-implementation and controller layers.

**Comment by arpanghosh2416** [comment]
I would like to contribute this issue. I have a design ready.

**Comment by arpanghosh2414** [comment]
Ok. I am assigning it to you.

**Comment by arpanghosh2414** [comment]
Thank You.
